In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# See sheet names
xls = pd.ExcelFile('Online retail.xlsx')
print(xls.sheet_names)

['Sheet1']

In [9]:
# load dataset
df = pd.read_excel("Online retail.xlsx")

In [10]:
df.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [11]:
df.size

7500

## Data Preprocessing:

In [12]:
# missing values:
df.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [16]:
# handling duplicate
df.duplicated().sum()

np.int64(2325)

In [18]:
df.drop_duplicates(inplace = True , ignore_index = True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.describe

<bound method NDFrame.describe of      shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
5170  burgers,salmon,pancakes,french fries,frozen sm...
5171  turkey,burgers,dessert wine,shrimp,pasta,tomat...
5172                      butter,light mayo,fresh bread
5173  burgers,frozen vegetables,eggs,french fries,ma...
5174    eggs,frozen smoothie,yogurt cake,low fat yogurt

[5175 rows x 1 columns]>

In [30]:
# Converts the dataset into list-of-lists
        # format required for Association Rule Mining.
transactions = []

for i in range(len(df)):
    transactions.append([str(df.iloc[i,j]) for j in range(len(df.columns))])

In [31]:
# one long list
        # To collect all individual items.
items1 = [items for trans in transactions for items in trans]
# Get Unique Items
        # To know how many different products exist in the dataset.
items2 = list(set(item1))

In [32]:
# Remove 'Nan'
if 'nan' in items2:
    items2.remove('nan')

In [33]:
len(items2)

5175

In [34]:
len(items1)

5175

In [35]:
print(items2)

['ground beef,mineral water,cottage cheese,magazines', 'vegetables mix,eggs,whole wheat rice', 'shrimp,whole wheat pasta,soup,milk,french fries', 'burgers,french fries,frozen smoothie,hot dogs,strawberries,green tea', 'spaghetti,whole wheat rice,corn,champagne', 'herb & pepper,ground beef,spaghetti,chocolate,milk,eggs,light cream', 'fresh tuna,herb & pepper,mineral water,olive oil,chicken,muffins,chocolate,yogurt cake', 'pepper,spaghetti,mineral water,milk,pancakes,cake,white wine,green tea', 'burgers,spaghetti,mineral water,almonds,honey,extra dark chocolate,carrots,mashed potato', 'eggs,tea', 'burgers,mineral water', 'green tea,mushroom cream sauce', 'red wine,mineral water,champagne,mushroom cream sauce', 'frozen smoothie,brownies', 'mineral water,soup,gums,extra dark chocolate,french fries', 'frozen vegetables,spaghetti,mineral water,avocado,chocolate,french fries,cookies,melons', 'pickles,herb & pepper,shrimp,milk,spinach,cake,chili,green tea,light mayo', 'frozen vegetables,spaghetti,french fries,light mayo,green tea', 'frozen vegetables,mineral water,chicken,whole wheat rice', 'avocado,brownies', 'herb & pepper,shrimp,whole wheat pasta,whole wheat rice,chicken,green tea,cauliflower', 'turkey,spaghetti', 'frozen vegetables,whole wheat rice,cooking oil,cereals,protein bar,magazines,low fat yogurt', 'frozen vegetables,cider,eggs,french fries', 'herb & pepper,ground beef,mineral water,chocolate,milk,french fries,low fat yogurt', 'chocolate,spaghetti,eggs,green tea', 'parmesan cheese,mineral water,champagne,white wine,low fat yogurt', 'burgers,pancakes,green tea,french fries', 'mineral water,salmon', 'milk,light cream,chicken,extra dark chocolate', 'grated cheese,french fries', 'spaghetti,oil,cooking oil,white wine', 'turkey,soup,spinach,french fries,salt', 'cookies,low fat yogurt', 'whole wheat pasta,milk,pancakes,low fat yogurt', 'frozen vegetables,spaghetti,mineral water,cake,rice,zucchini', 'grated cheese,herb & pepper,ground beef', 'french fries,mayonnaise', 'burgers,eggs,french fries,cookies,green tea', 'french fries,tomato juice,fresh bread', 'milk,butter,eggs,whole wheat rice', 'soup,melons,salad', 'herb & pepper,ground beef,spaghetti,honey,french fries,pancakes,low fat yogurt', 'spaghetti,cake,pancakes,white wine', 'ground beef,spaghetti,yogurt cake', 'green tea,cottage cheese', 'tomatoes,spaghetti,milk,olive oil,pancakes,whole wheat rice,green tea,yogurt cake,mint', 'burgers,tomatoes,mineral water,soup,milk,almonds,eggs,chocolate,tomato juice', 'french fries,yogurt cake', 'chili,french fries,green tea', 'whole wheat pasta,olive oil,green tea,chocolate,french fries,champagne,hot dogs,tomato juice', 'chili', 'cooking oil,french fries', 'spaghetti,mineral water,chocolate,french fries,champagne,escalope,mushroom cream sauce,fresh bread', 'parmesan cheese,whole wheat rice,escalope,champagne', 'fresh tuna,ground beef,pepper,tomato sauce,chicken,soda,mint', 'grated cheese,frozen vegetables,ground beef,olive oil,salmon,blueberries', 'shrimp,french fries,champagne,cookies,pancakes,yogurt cake,light mayo,green tea', 'spaghetti,mineral water,milk,olive oil,eggs,brownies,melons', 'grated cheese,mineral water,honey,cake,whole weat flour,salad', 'turkey,herb & pepper,gums', 'soda,cottage cheese', 'frozen vegetables,ground beef,milk,chicken,fromage blanc,whole wheat rice,ketchup,hot dogs,brownies,light mayo', 'frozen vegetables,tomatoes,mineral water,chicken,green grapes,eggs,chocolate,brownies,fresh bread,white wine', 'herb & pepper,milk,cake,french fries,yogurt cake', 'spaghetti,eggs,french fries', 'fresh tuna,frozen vegetables,energy bar,honey,cake,brownies,yogurt cake,energy drink', 'spaghetti,soup,milk,butter,whole wheat rice,chocolate,low fat yogurt,green tea', 'turkey,ham,frozen vegetables,whole wheat pasta,spaghetti,mineral water,olive oil,pancakes,cooking oil,ketchup,champagne,cookies,hot dogs', 'champagne,cookies,green tea', 'whole wheat pasta,ground beef,mineral water,avocado,milk,olive oil,chicken,gums,frozen smoothie', 'turkey,burgers,spaghetti,honey,carrots,brownies,green tea', 'chocolate,frozen smoothie,champagne', 'ham,frozen vegetables,spaghetti,light mayo', 'salt,green tea', 'grated cheese,frozen vegetables,parmesan cheese,ground beef,spaghetti,mineral water,chocolate,milk,eggs', 'ham,mineral water,almonds,whole wheat rice,cake,frozen smoothie,low fat yogurt', 'chocolate,asparagus', 'grated cheese,mineral water,chocolate,chutney,salmon,eggs,whole wheat rice,cake', 'green tea,champagne,escalope', 'spaghetti,chicken,honey,oatmeal,green tea,chocolate,french fries,frozen smoothie,cookies,mushroom cream sauce,magazines', 'french wine,bug spray,green beans', 'grated cheese,spaghetti,mineral water,whole wheat rice,cake,french fries,champagne', 'frozen vegetables,muffins,green grapes,light mayo', 'fresh tuna,spaghetti,mineral water,pancakes,whole weat flour,champagne,hot dogs,tomato juice,green tea', 'burgers,corn,low fat yogurt', 'fresh tuna,mineral water,pancakes,tea,chocolate,escalope', 'whole wheat pasta,olive oil,oil,clothes accessories,pasta,white wine,green tea', 'shrimp,frozen vegetables,mineral water,vegetables mix,eggs,whole wheat rice', 'pancakes,cake,cooking oil', 'butter,bacon,eggs,carrots,french fries,tomato juice,green tea', 'dessert wine,grated cheese,shrimp,spaghetti,milk,champagne', 'milk,black tea,eggs,energy drink', 'shrimp,frozen vegetables,mineral water,soup,milk,pancakes,chocolate,french fries,green tea', 'ground beef,mineral water,protein bar', 'parmesan cheese,eggs,cake,escalope', 'grated cheese,olive oil,eggs,oil,french fries,cottage cheese,pancakes,light mayo', 'grated cheese,mineral water,cooking oil', 'shrimp,tomatoes,spaghetti,eggs', 'frozen vegetables,whole wheat rice,cake', 'spaghetti,mineral water,pancakes,cooking oil,chocolate,frozen smoothie,escalope', 'light cream', 'cake,chocolate,low fat yogurt', 'frozen vegetables,ground beef,chocolate,rice,french fries,fresh bread', 'shrimp,frozen vegetables,parmesan cheese,spaghetti,salmon,carrots,frozen smoothie,pasta,mashed potato,shallot,light mayo,magazines', 'muffins,french fries,escalope,gluten free bar', 'chocolate,frozen smoothie,escalope', 'mineral water,soup,milk,salmon,cooking oil,ketchup,cereals,eggplant,french fries,magazines', 'milk,strawberries,low fat yogurt', 'cake,oil,escalope,pancakes,yogurt cake', 'red wine,honey,hot dogs', 'burgers,butter,escalope,cauliflower', 'tomatoes,soup,cooking oil,extra dark chocolate', 'pepper,cider', 'turkey,grated cheese,shrimp,spaghetti,pancakes,cake,ketchup,carrots,french fries,low fat yogurt', 'cooking oil,toothpaste,low fat yogurt', 'fresh tuna,shrimp,frozen vegetables,tomatoes,tomato sauce,spaghetti,mineral water,milk,cider,whole wheat rice,clothes accessories,frozen smoothie', 'avocado', 'turkey,eggs,cake', 'muffins,honey', 'ham,red wine,corn,green tea', 'cereals,pancakes,yogurt cake', 'burgers,fresh tuna,grated cheese,spaghetti,mineral water,avocado,olive oil,gums,frozen smoothie,hot dogs,cottage cheese', 'ham,ground beef,spaghetti,olive oil,vegetables mix,muffins', 'frozen vegetables,mineral water,soup,avocado,cake,french fries,champagne,tomato juice,green tea', 'fresh tuna,spinach,honey,cake,cereals,chocolate,french fries,light mayo,green tea', 'spaghetti,green tea,french fries,shampoo', 'ham,ground beef,mineral water,soup,cake', 'tomato sauce,champagne,green tea', 'honey,chocolate,french fries,escalope', 'ground beef,soup,avocado,olive oil,cake,chocolate bread,green tea,french fries,frozen smoothie,low fat yogurt', 'turkey,burgers,red wine,tomatoes,spaghetti,mineral water,avocado,vegetables mix,pancakes,french fries', 'pancakes,eggs,light cream', 'grated cheese,mineral water,avocado,salmon,chocolate,asparagus', 'ham,herb & pepper,whole wheat pasta,spaghetti,soup,milk,olive oil,butter,whole wheat rice', 'frozen vegetables,ground beef,mineral water,chocolate,pancakes', 'meatballs,almonds', 'shrimp,gums,low fat yogurt', 'grated cheese,herb & pepper,mineral water,salmon,chicken,cookies,protein bar,fresh bread,zucchini', 'whole weat flour,brownies', 'mineral water,milk,energy bar,barbecue sauce,chocolate,low fat yogurt', 'turkey,red wine,parmesan cheese,spaghetti,mineral water,meatballs,olive oil,bacon,honey,blueberries,chocolate bread,hot dogs,brownies,pancakes', 'pepper,spaghetti,cake,chocolate,french fries,fresh bread', 'tomatoes,eggs,antioxydant juice,french fries,brownies,gluten free bar,fresh bread', 'burgers,grated cheese,spaghetti,avocado,milk,oil,french fries', 'dessert wine,frozen vegetables,milk,muffins,eggs', 'herb & pepper,shrimp,ground beef,yogurt cake', 'frozen vegetables,olive oil,oatmeal', 'ham,whole wheat rice,melons,green tea', 'ground beef,mint', 'whole wheat pasta,butter,gums,cereals,body spray,green tea', 'turkey,ground beef,spaghetti,soup,escalope,yogurt cake', 'grated cheese,ground beef,whole wheat rice,french fries,escalope', 'turkey,ham,shrimp,tomatoes,whole wheat rice,carrots,green tea,yogurt cake,low fat yogurt', 'cake,chicken,green tea,shallot', 'turkey,burgers,herb & pepper,frozen vegetables,whole wheat pasta,ground beef,spaghetti,mineral water,milk,energy bar,black tea,strong cheese,nonfat milk,eggs', 'muffins', 'frozen vegetables,tomatoes,green tea,french fries,frozen smoothie,hot dogs', 'burgers,milk,cake,cereals', 'soup,strawberries,yogurt cake,low fat yogurt', 'olive oil,light mayo', 'ground beef,spaghetti,eggplant,green tea', 'herb & pepper,parmesan cheese,frozen smoothie', 'turkey,chocolate,whole wheat rice', 'eggs,cookies', 'soup,hot dogs', 'frozen vegetables,tomatoes,butter,eggs,cake,bug spray', 'shrimp,french fries,champagne', 'frozen vegetables,mineral water,almonds,bacon,eggs,barbecue sauce', 'muffins,whole wheat rice,chocolate,french fries', 'green beans,chocolate', 'shrimp,meatballs,honey,eggplant,chocolate,sandwich,babies food', 'honey,chocolate,french fries,brownies', 'shrimp,ground beef,pepper,spaghetti', 'grated cheese,spaghetti,mineral water,salmon,whole wheat rice,blueberries,green beans,sandwich,pancakes,shampoo', 'shrimp,frozen vegetables,tomatoes,parmesan cheese,ground beef,spaghetti,eggs,cake,oatmeal,cereals', 'mineral water,eggs,whole wheat rice,cooking oil', 'pepper', 'grated cheese,butter,chocolate,french fries,cookies', 'whole wheat pasta,antioxydant juice,body spray,green tea', 'shrimp,chocolate,white wine', 'cake,french fries,cookies,champagne,low fat yogurt', 'soup,eggs', 'mineral water,chocolate,whole wheat rice,cake,whole weat flour,french fries,low fat yogurt', 'turkey,grated cheese,herb & pepper,frozen vegetables,spaghetti,mineral water,milk,eggs,gums,carrots,french fries,low fat yogurt', 'tomatoes,ground beef,meatballs,salmon,eggs,champagne,frozen smoothie,low fat yogurt,mint', 'ground beef,spaghetti,mineral water,milk,frozen smoothie,champagne', 'herb & pepper,shrimp,tomatoes,milk,eggs,light cream,cooking oil,chili,chocolate', 'frozen vegetables,mineral water,milk,muffins,chocolate,french fries,tomato juice,fresh bread', 'red wine,mineral water,milk,black tea,spinach,rice,green beans,frozen smoothie,sparkling water', 'herb & pepper,shrimp,ground beef,chocolate,french fries,frozen smoothie,mint', 'milk,cooking oil,chocolate,strawberries', 'herb & pepper,tomatoes,pepper,mineral water,cooking oil,french fries,frozen smoothie,fresh bread', 'green tea,fresh bread', 'eggs,cake,fresh bread,low fat yogurt', 'tomatoes,ground beef,pepper,spaghetti,salmon,cake', 'spaghetti,fromage blanc,tea', 'mineral water,extra dark chocolate,brownies,asparagus,low fat yogurt', 'mineral water,avocado,olive oil,muffins,green tea,french fries,escalope', 'frozen vegetables,soup,milk,olive oil', 'shrimp,frozen vegetables,milk,nonfat milk,eggs,green beans,french fries,frozen smoothie,mushroom cream sauce,pancakes,light mayo,melons,tomato juice', 'turkey,shrimp,spaghetti,butter,melons,low fat yogurt', 'milk,melons', 'red wine,flax seed,cake,frozen smoothie,hot dogs,toothpaste', 'turkey,cooking oil,low fat yogurt,green tea', 'burgers,spaghetti,eggs,frozen smoothie', 'chocolate,shrimp,pasta,spaghetti', 'turkey,frozen vegetables,ground beef,meatballs,energy bar,whole wheat rice,frozen smoothie', 'burgers,chocolate,spaghetti,mineral water,olive oil,pancakes,eggs,mayonnaise', 'burgers,tomatoes,spaghetti,milk,barbecue sauce,frozen smoothie,green tea', 'mineral water,eggs,honey,protein bar', 'frozen vegetables,chicken,pancakes', 'champagne,pancakes,green tea', 'mineral water,soup,cake,frozen smoothie,low fat yogurt', 'vegetables mix,french fries', 'fromage blanc,chocolate,french fries', 'mineral water,pancakes,french fries,cookies,shallot,green tea', 'french fries,cottage cheese,green tea', 'eggs,cookies,green tea,honey', 'fresh tuna,avocado,vegetables mix,green grapes,honey,whole weat flour,french fries,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,oil,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,cereals', 'cereals,salt,green tea', 'herb & pepper,ground beef,spaghetti,mineral water,chocolate,black tea,french wine,pancakes,rice,green tea,toothpaste', 'red wine,ground beef,spaghetti,mineral water,milk,olive oil,strong cheese,light cream,cooking oil', 'french fries,zucchini', 'chocolate,french fries,mushroom cream sauce,cottage cheese,low fat yogurt', 'pancakes,hot dogs,sparkling water,fresh bread', 'shrimp,milk,olive oil,french fries', 'turkey,burgers,eggs,french fries,shallot,energy drink,green tea', 'burgers,eggs,cake,chocolate', 'mashed potato', 'tomatoes,spaghetti,mineral water,salmon,strawberries', 'spaghetti,mineral water,soup,pancakes,tomato juice', 'cookies,hot dogs,green tea', 'mineral water,chicken,chocolate,escalope', 'herb & pepper,eggs,clothes accessories,french fries', 'chocolate,cottage cheese,pancakes', 'frozen vegetables,tomatoes,spaghetti,mineral water,muffins,cake,mushroom cream sauce', 'french fries,pancakes,light mayo', 'salmon', 'black tea,muffins', 'avocado,yogurt cake', 'herb & pepper,spaghetti,mineral water,eggs', 'turkey,burgers,grated cheese,pepper,spaghetti,eggs,gums,low fat yogurt,green tea', 'herb & pepper,ground beef,soup,avocado,brownies,salt', 'shrimp,frozen vegetables,tomatoes,ground beef,spaghetti', 'vegetables mix,eggs,escalope', 'fromage blanc,eggs,french fries', 'milk,energy bar,eggs,frozen smoothie,mint', 'shrimp,frozen vegetables,tomatoes,cottage cheese', 'pepper,mineral water,pancakes,eggs,cooking oil,chocolate,low fat yogurt', 'burgers,dessert wine,spaghetti,chicken,cake,protein bar,green tea', 'grated cheese,energy bar,honey', 'vegetables mix', 'shrimp,body spray,green tea', 'chocolate,shrimp,cereals,champagne,green tea', 'burgers,frozen vegetables,tomatoes,ground beef,olive oil,cake,cereals,antioxydant juice,escalope', 'frozen vegetables,spaghetti,eggs', 'spaghetti,chocolate,olive oil,fromage blanc', 'tomatoes,escalope', 'shrimp,tomato sauce,spaghetti,soup', 'shrimp,champagne', 'pickles', 'mineral water,avocado,milk,olive oil,strong cheese,cauliflower', 'grated cheese,frozen vegetables,honey,french fries,escalope', 'herb & pepper,mineral water', 'avocado,black tea,eggs', 'burgers,milk,cake,cooking oil,french fries,escalope,zucchini', 'grated cheese,shrimp,pasta,tomatoes,milk,frozen smoothie,sandwich', 'spaghetti,mineral water,soup,olive oil,pancakes,eggs', 'mineral water,cookies', 'frozen vegetables,tomatoes,spaghetti,salmon,muffins,whole wheat rice,cake,light cream,carrots,green tea,french fries,champagne,frozen smoothie', 'butter,whole wheat rice', 'turkey,burgers,fresh tuna,french wine,fromage blanc', 'burgers,eggs,frozen smoothie,body spray', 'whole wheat pasta,spaghetti,milk,nonfat milk,oil,cooking oil,hot dogs', 'herb & pepper,frozen vegetables,mineral water,muffins,cereals', 'soup,olive oil,light mayo,zucchini,green tea', 'milk,almonds,vegetables mix', 'shrimp,mineral water,pancakes,yogurt cake,green tea', 'frozen vegetables,mineral water,milk', 'turkey,eggs,chocolate,frozen smoothie,tomato juice', 'spaghetti,yams,mineral water,honey', 'mineral water,chocolate,milk,vegetables mix,eggs,soda,cooking oil,carrots,frozen smoothie,escalope', 'herb & pepper,chocolate,champagne,yogurt cake,green tea', 'spaghetti,eggs,cake,escalope', 'chocolate bread,hand protein bar', 'eggs,cooking oil,eggplant', 'ground beef,pancakes,honey', 'milk,cake,green tea', 'eggs,french fries,brownies,strawberries', 'tomatoes,champagne', 'avocado,eggs,fresh bread,low fat yogurt,green tea', 'french fries,cookies,mushroom cream sauce,honey', 'ham,milk', 'black tea,french wine,chocolate,french fries,shallot,brownies,pancakes,toothpaste', 'herb & pepper,spaghetti,pancakes,cake', 'turkey,tomato juice', 'burgers,ham,red wine', 'muffins,gums', 'grated cheese,tomato juice', 'whole wheat rice,oil,chicken,french fries,escalope', 'tomatoes,mineral water,olive oil,extra dark chocolate', 'ham,eggs,cake', 'champagne,energy drink', 'spaghetti,olive oil,fromage blanc,pancakes,eggs,cereals,clothes accessories,yogurt cake,gluten free bar,fresh bread,green tea', 'ground beef,mineral water,chocolate,milk,chicken,nonfat milk,green tea', 'energy bar,whole wheat rice,cake,french fries,low fat yogurt,green tea', 'burgers,mineral water,cooking oil', 'fresh tuna,herb & pepper,spaghetti,low fat yogurt', 'champagne,protein bar', 'eggs,hot dogs', 'spaghetti,escalope,mayonnaise', 'nonfat milk,eggs,cake', 'escalope,low fat yogurt', 'burgers,herb & pepper,frozen vegetables,pepper,salmon,pancakes,honey,gums,chicken,extra dark chocolate,eggplant,green tea,melons', 'frozen vegetables,mineral water,muffins', 'whole wheat pasta,mineral water,olive oil,cake,french fries,strawberries,pancakes,light mayo', 'burgers,ground beef,mineral water,milk', 'turkey,tomatoes,spaghetti,mineral water', 'ham,whole wheat rice,french fries,champagne,cauliflower', 'shrimp,spaghetti,salmon,chicken', 'honey,cottage cheese,green tea', 'flax seed,eggs,chicken,cereals', 'tomatoes,chocolate,black tea,honey,champagne', 'salmon,vegetables mix', 'avocado,milk', 'burgers,red wine,ground beef,pepper,ham,fresh bread,low fat yogurt', 'milk,chocolate', 'parmesan cheese,spaghetti,soup,avocado,milk,fresh bread', 'red wine,carrots,tomato juice', 'dessert wine,frozen vegetables,tomatoes,parmesan cheese,mineral water,soup,olive oil,salmon,extra dark chocolate', 'mineral water,olive oil,eggs,mint', 'burgers,fresh tuna,avocado', 'chocolate,spaghetti,bug spray', 'herb & pepper,mineral water,eggs,cake,cereals,brownies,pancakes,tomato juice,low fat yogurt,green tea', 'pepper,spaghetti,mineral water,chili,escalope,mint', 'milk,cake,chili,protein bar,zucchini', 'yams', 'chicken,eggs,french fries,strawberries', 'grated cheese,spinach,eggs,cooking oil,green tea,salad', 'herb & pepper,frozen vegetables,salmon,carrots,chocolate,french fries', 'frozen vegetables,tomatoes,ground beef,pepper,spaghetti,mineral water,olive oil,champagne,frozen smoothie,mushroom cream sauce,hot dogs,protein bar,green tea', 'mineral water,tea,escalope,fresh bread,magazines', 'mineral water,vegetables mix,low fat yogurt', 'spaghetti,avocado,brownies', 'chocolate,frozen smoothie,low fat yogurt', 'whole wheat pasta,salmon,antioxydant juice,mint green tea', 'ground beef,chocolate,soup,cake,pancakes,cauliflower', 'turkey,ham,mineral water,chocolate,milk,chicken,eggs,cake', 'burgers,eggs,green tea', 'almonds,eggs', 'frozen smoothie,mint', 'burgers,ham,ground beef,spaghetti,mineral water,meatballs,milk,cake,brownies', 'burgers,almonds,eggs,chicken,light mayo', 'pickles,champagne,green tea', 'turkey,green grapes,champagne,strawberries,green tea', 'pepper,cereals,antioxydant juice,sparkling water,shampoo', 'energy bar', 'chocolate,milk,eggs,french fries', 'burgers,milk,cream', 'milk', 'whole wheat pasta,spaghetti,meatballs,milk,chocolate', 'spaghetti,soup,chili,eggplant', 'cereals,champagne', 'ground beef,mineral water,eggs,yogurt cake', 'burgers,eggs,cooking oil', 'chocolate,french fries,hot dogs', 'avocado,energy drink,low fat yogurt', 'chocolate,tomatoes,ground beef,tomato sauce,mineral water,salmon,pancakes', 'burgers,spaghetti,green grapes,cake,frozen smoothie,cottage cheese', 'pancakes,eggs', 'chocolate,milk,oliv

In [36]:
df.duplicated().sum()

np.int64(0)

In [40]:
print(transactions[:5])

[['burgers,meatballs,eggs'], ['chutney'], ['turkey,avocado'], ['mineral water,milk,energy bar,whole wheat rice,green tea'], ['low fat yogurt']]

In [41]:
# splits each transaction’s comma-separated string into a list of individual items
transactions = [t[0].split(',') for t in transactions]

In [43]:
## install mlxtend
!pip install mlxtend

Requirement already satisfied: mlxtend in /opt/anaconda3/lib/python3.13/site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.1.3)
Requirement already satisfied: pandas>=0.24.2 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.3.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [45]:
# importing Transaction,apriori and association_rules
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [46]:
data = TransactionEncoder()

In [48]:
data_ary = data.fit(transactions).transform(transactions)
data1 = pd.DataFrame(data_ary, columns = data.columns_)

In [49]:
data1.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [53]:
# items often bought together
freq_patterns = apriori(data1, min_support=0.0005, use_colnames=True)

In [55]:
# top frequent itemsets
freq_patterns.sort_values('support', ascending=False).head()

     support         itemsets
71  0.299710  (mineral water)
99  0.229565      (spaghetti)
36  0.208116           (eggs)
24  0.205217      (chocolate)
42  0.192657   (french fries)

In [57]:
# only itemsets with more than one item
freq_patterns[freq_patterns['itemsets'].apply(lambda x: len(x) > 1)]

        support                                           itemsets
119    0.002319                                 (avocado, almonds)
120    0.000773                          (almonds, barbecue sauce)
121    0.001353                               (almonds, black tea)
122    0.000966                                (almonds, brownies)
123    0.000773                               (almonds, bug spray)
...         ...                                                ...
36118  0.000580  (milk, turkey, vegetables mix, frozen vegetabl...
36119  0.000580  (milk, turkey, vegetables mix, frozen vegetabl...
36120  0.000580  (turkey, vegetables mix, frozen vegetables, wh...
36121  0.000580  (milk, turkey, vegetables mix, whole wheat ric...
36122  0.000580  (milk, turkey, vegetables mix, frozen vegetabl...

[36004 rows x 2 columns]

In [59]:
# Generates association rules
rules = association_rules(freq_patterns,metric='confidence',min_threshold=0.1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(burgers),0.029179,0.113816,0.007536,0.258278,2.269252,1.0,0.004215,1.194765,0.576137,0.055635,0.163016,0.162246
1,(almonds),(cake),0.029179,0.103575,0.004444,0.152318,1.470606,1.0,0.001422,1.057502,0.329626,0.034639,0.054375,0.097614
2,(almonds),(chicken),0.029179,0.083865,0.003478,0.119205,1.421400,1.0,0.001031,1.040123,0.305379,0.031746,0.038576,0.080340
3,(almonds),(chocolate),0.029179,0.205217,0.008696,0.298013,1.452183,1.0,0.002708,1.132190,0.320740,0.038527,0.116756,0.170193
4,(almonds),(eggs),0.029179,0.208116,0.009469,0.324503,1.559243,1.0,0.003396,1.172299,0.369443,0.041561,0.146975,0.185000

In [60]:
print(data1.columns[:20])

Index([' asparagus', 'almonds', 'antioxydant juice', 'asparagus', 'avocado',
       'babies food', 'bacon', 'barbecue sauce', 'black tea', 'blueberries',
       'body spray', 'bramble', 'brownies', 'bug spray', 'burger sauce',
       'burgers', 'butter', 'cake', 'candy bars', 'carrots'],
      dtype='object')

In [61]:
print(len(transactions))

5175

# Analysis and Interpretation:

The rules show which items are commonly bought together. For example, almonds are frequently purchased with burgers, cake, chocolate, and eggs. A higher confidence indicates that if one item is bought, the other is likely to be bought too, while a lift > 1 confirms a strong positive association between the items.

Customers who buy almonds tend to also buy chocolate and eggs, suggesting these may be part of regular meal or snack combinations.

Products with high lift can be placed near each other in stores or suggested together in online carts.

Interview Questions

1. What is lift and why is it important in Association rules?

    Lift is a metric used in association rule mining to measure how much more often two items occur together than would be expected if they were independent.
    Lift helps reveal meaningful, non-random relationships between items. Even if confidence is high, a rule is only useful when lift > 1, showing the items are bought together more often than expected. This makes lift valuable for decisions like product bundling and recommendations.

2. What is support and Confidence. How do you calculate them?


   1. Support
      Support shows how frequently an item or itemset appears in the dataset.
      -dividing the number of transactions containing the itemset by the total number of transactions
  
      

   3. Confidence
    Confidence measures how likely item B is bought when item A is bought.
       -dividing the support of the combined itemset (A and B) by the support of the antecedent (A)

3. What are some limitations or challenges of Association rules mining?

    * It can produce too many rules, making interpretation difficult.
    * Requires careful selection of support and confidence to get meaningful rules.
    * Does not consider item order or time, only co-occurrence.
    * Can be computationally expensive on large datasets.