In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the dataset
df = pd.read_csv("Alphabets_data.csv")
df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [4]:
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [5]:
df.shape

(20000, 17)

In [6]:
# checking for missing values:
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [7]:
# checking for duplicates:
df.duplicated().sum()

np.int64(1332)

In [8]:
df.drop_duplicates(inplace= True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
# split the data into target and predictors:

y = df['letter']
x = df.drop('letter', axis=1)

In [11]:
# after spliting convert the categorical variable to numerical using label encoding

from sklearn.preprocessing import LabelEncoder, StandardScaler

le = LabelEncoder()
y = le.fit_transform(y)

## 2. Model Implementation

In [12]:
# split the dataset to train and test:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2,random_state = 42, stratify = y
)

In [13]:
# normalize :
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [15]:
# Define model 
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),  
    Dense(len(np.unique(y)), activation='softmax')                  
])

/opt/anaconda3/envs/tfenv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
# compile model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [18]:
history = model.fit(x_train, y_train,
                    epochs=30,
                    batch_size=32,
                    validation_split=0.2,
                    verbose=1)

Epoch 1/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 1s 714us/step - accuracy: 0.4076 - loss: 2.2402 - val_accuracy: 0.6307 - val_loss: 1.5066
Epoch 2/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.6828 - loss: 1.2191 - val_accuracy: 0.7218 - val_loss: 1.0655
Epoch 3/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.7489 - loss: 0.9292 - val_accuracy: 0.7529 - val_loss: 0.8980
Epoch 4/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.7808 - loss: 0.7887 - val_accuracy: 0.7811 - val_loss: 0.8017
Epoch 5/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.8045 - loss: 0.6991 - val_accuracy: 0.7951 - val_loss: 0.7310
Epoch 6/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.8230 - loss: 0.6337 - val_accuracy: 0.8108 - val_loss: 0.6706
Epoch 7/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.8359 - loss: 0.5821 - val_accuracy: 0.8252 - val_loss: 0.6288
Epoch 8/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step - accuracy: 0.8476 - loss: 0.5395 - val_accuracy: 0.8333 - val_loss: 0.5915
Epoch 9/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.8593 - loss: 0.5034 - val_accuracy: 0.8386 - val_loss: 0.5601
Epoch 10/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.8674 - loss: 0.4728 - val_accuracy: 0.8460 - val_loss: 0.5348
Epoch 11/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.8731 - loss: 0.4462 - val_accuracy: 0.8524 - val_loss: 0.5084
Epoch 12/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.8809 - loss: 0.4218 - val_accuracy: 0.8577 - val_loss: 0.4905
Epoch 13/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.8870 - loss: 0.4018 - val_accuracy: 0.8627 - val_loss: 0.4751
Epoch 14/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.8937 - loss: 0.3833 - val_accuracy: 0.8654 - val_loss: 0.4604
Epoch 15/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.8962 - loss: 0.3663 - val_accuracy: 0.8714 - val_loss: 0.4432
Epoch 16/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.9004 - loss: 0.3507 - val_accuracy: 0.8731 - val_loss: 0.4306
Epoch 17/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.9052 - loss: 0.3360 - val_accuracy: 0.8781 - val_loss: 0.4201
Epoch 18/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.9089 - loss: 0.3237 - val_accuracy: 0.8771 - val_loss: 0.4098
Epoch 19/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.9119 - loss: 0.3116 - val_accuracy: 0.8868 - val_loss: 0.3953
Epoch 20/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9164 - loss: 0.3005 - val_accuracy: 0.8858 - val_loss: 0.3871
Epoch 21/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.9183 - loss: 0.2907 - val_accuracy: 0.8845 - val_loss: 0.3806
Epoch 22/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.9222 - loss: 0.2806 - val_accuracy: 0.8902 - val_loss: 0.3700
Epoch 23/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - accuracy: 0.9229 - loss: 0.2720 - val_accuracy: 0.8905 - val_loss: 0.3725
Epoch 24/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.9259 - loss: 0.2630 - val_accuracy: 0.8929 - val_loss: 0.3589
Epoch 25/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.9284 - loss: 0.2563 - val_accuracy: 0.8939 - val_loss: 0.3516
Epoch 26/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.9296 - loss: 0.2502 - val_accuracy: 0.8935 - val_loss: 0.3507
Epoch 27/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.9319 - loss: 0.2431 - val_accuracy: 0.8939 - val_loss: 0.3475
Epoch 28/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.9320 - loss: 0.2368 - val_accuracy: 0.8949 - val_loss: 0.3403
Epoch 29/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.9332 - loss: 0.2309 - val_accuracy: 0.8972 - val_loss: 0.3377
Epoch 30/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.9353 - loss: 0.2249 - val_accuracy: 0.9022 - val_loss: 0.3293

In [22]:
from sklearn.metrics import accuracy_score, recall_score,f1_score,precision_score,confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

y_pred = np.argmax(model.predict(x_test), axis=1)
test_accuracy = accuracy_score(y_test, y_pred)
prec_best = precision_score(y_test, y_pred, average='macro')
rec_best = recall_score(y_test, y_pred, average='macro')
f1_best = f1_score(y_test, y_pred, average='macro')
print("🔹 Tuned Model Performance:")
print(f"Accuracy: {test_accuracy:.4f}")
print(f"Precision: {prec_best:.4f}")
print(f"Recall: {rec_best:.4f}")
print(f"F1-score: {f1_best:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step
🔹 Tuned Model Performance:
Accuracy: 0.9036
Precision: 0.9061
Recall: 0.9030
F1-score: 0.9036

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94       151
           1       0.81      0.92      0.86       146
           2       0.86      0.95      0.90       142
           3       0.90      0.92      0.91       152
           4       0.87      0.84      0.85       145
           5       0.82      0.88      0.85       150
           6       0.82      0.84      0.83       149
           7       0.87      0.82      0.85       141
           8       0.94      0.86      0.90       105
           9       0.92      0.94      0.93       143
          10       0.88      0.94      0.91       144
          11       0.95      0.89      0.92       134
          12       0.94      0.93      0.93       146
          13       0.93      0.90      0.92       138
          14       0.88      0.85      0.87       144
          15       0.96      0.88      0.92       156
          16       0.91      0.89      0.90       152
          17       0.90      0.88      0.89       147
          18       0.89      0.92      0.90       146
          19       0.90      0.94      0.92       150
          20       0.97      0.95      0.96       154
          21       0.97      0.87      0.92       141
          22       0.91      0.99      0.94       145
          23       0.95      0.85      0.90       136
          24       0.93      0.94      0.93       149
          25       0.93      0.95      0.94       128

    accuracy                           0.90      3734
   macro avg       0.91      0.90      0.90      3734
weighted avg       0.91      0.90      0.90      3734

## 3. Hyperparameter Tuning

In [23]:
from tensorflow import keras
def create_model(activation='relu', optimizer='adam',neurons=64):
    model = keras.Sequential([
        keras.layers.Dense(neurons, input_dim=x_train.shape[1], activation=activation),
         keras.layers.Dense(len(np.unique(y_train)), activation='softmax')
    ])
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

In [24]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from scikeras) (3.12.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from scikeras) (1.7.2)
Requirement already satisfied: absl-py in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (2.3.1)
Requirement already satisfied: numpy in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (2.2.6)
Requirement already satisfied: rich in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (14.2.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (3.15.1)
Requirement already satisfied: optree in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (0.17.0)
Requirement already satisfied: ml-dtypes in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (0.5.3)
Requirement already satisfied: packaging in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from keras>=3.2.0->scikeras) (25.0)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from rich->keras>=3.2.0->scikeras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/tfenv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [25]:
from scikeras.wrappers import KerasClassifier
keras_clf = KerasClassifier(model=create_model, verbose=0)

In [26]:
param_grid = {
    'model__activation': ['relu', 'tanh'],
    'model__optimizer': ['adam', 'sgd'],
     'model__neurons': [32, 64, 128],
    'batch_size': [16, 32],
    'epochs': [30,50]
}

In [28]:
from sklearn.model_selection import train_test_split,GridSearchCV, RandomizedSearchCV, StratifiedKFold
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
grid = GridSearchCV(estimator=keras_clf,
                    param_grid=param_grid,
                    scoring='accuracy',
                    cv=cv,   
                    verbose=2)
grid_result = grid.fit(x_train, y_train)

Fitting 3 folds for each of 48 candidates, totalling 144 fits
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   7.6s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   7.4s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   7.5s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.9s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.7s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.7s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   7.7s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   7.5s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   7.5s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   6.9s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   7.0s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   7.0s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.9s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.8s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.7s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   7.2s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   7.5s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   7.4s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   7.5s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   6.9s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   7.0s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   6.9s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   8.2s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   7.9s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   7.6s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   7.0s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   7.0s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.8s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.8s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.7s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   7.1s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=  12.0s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=  12.1s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=  12.0s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=  11.1s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=  11.1s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=  11.2s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=  12.2s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=  12.2s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=  12.2s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=  11.3s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=  11.6s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=  11.4s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=  12.6s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=  12.6s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=  12.5s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=  11.6s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=  11.6s
[CV] END batch_size=16, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=  11.6s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=  12.1s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=  12.1s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=  12.0s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=  11.2s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=  11.1s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=  11.2s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=  12.2s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=  12.3s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=  12.3s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=  11.4s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=  11.4s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=  11.4s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=  12.6s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=  12.8s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=  12.7s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=  11.7s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=  11.7s
[CV] END batch_size=16, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=  11.7s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   4.3s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   4.3s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   4.7s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   4.5s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   4.4s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   4.1s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   4.0s
[CV] END batch_size=32, epochs=30, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   4.2s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   4.5s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   3.8s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   4.3s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   4.3s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   4.3s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   3.9s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   4.4s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   4.4s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   4.4s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   4.0s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   4.0s
[CV] END batch_size=32, epochs=30, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   4.0s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   6.7s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   6.7s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=adam; total time=   6.7s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.1s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.2s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=32, model__optimizer=sgd; total time=   6.1s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   6.5s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=64, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.1s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.4s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=adam; total time=   7.1s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   6.6s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   6.5s
[CV] END batch_size=32, epochs=50, model__activation=relu, model__neurons=128, model__optimizer=sgd; total time=   6.6s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   7.2s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   7.3s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   6.2s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=32, model__optimizer=sgd; total time=   6.2s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   6.9s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=adam; total time=   6.8s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=64, model__optimizer=sgd; total time=   6.3s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.1s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.4s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=adam; total time=   7.4s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   6.5s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   6.4s
[CV] END batch_size=32, epochs=50, model__activation=tanh, model__neurons=128, model__optimizer=sgd; total time=   6.5s

In [29]:
print("Best parameters:", grid_result.best_params_)
print("Best accuracy:", grid_result.best_score_)

Best parameters: {'batch_size': 16, 'epochs': 50, 'model__activation': 'tanh', 'model__neurons': 128, 'model__optimizer': 'adam'}
Best accuracy: 0.9442212401232087

In [30]:
best_model = grid_result.best_estimator_
y_pred_best = best_model.predict(x_test)
acc_best = accuracy_score(y_test, y_pred_best)
prec_best = precision_score(y_test, y_pred_best, average='macro')
rec_best = recall_score(y_test, y_pred_best, average='macro')
f1_best = f1_score(y_test, y_pred_best, average='macro')
print("🔹 Tuned Model Performance:")
print(f"Accuracy: {acc_best:.4f}")
print(f"Precision: {prec_best:.4f}")
print(f"Recall: {rec_best:.4f}")
print(f"F1-score: {f1_best:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_best))

🔹 Tuned Model Performance:
Accuracy: 0.9550
Precision: 0.9558
Recall: 0.9546
F1-score: 0.9550

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97       151
           1       0.93      0.93      0.93       146
           2       0.95      0.97      0.96       142
           3       0.96      0.98      0.97       152
           4       0.94      0.94      0.94       145
           5       0.93      0.95      0.94       150
           6       0.93      0.91      0.92       149
           7       0.92      0.93      0.93       141
           8       0.99      0.91      0.95       105
           9       0.92      0.97      0.95       143
          10       0.93      0.94      0.94       144
          11       0.96      0.96      0.96       134
          12       0.99      0.97      0.98       146
          13       0.96      0.96      0.96       138
          14       0.96      0.93      0.95       144
          15       0.97      0.95      0.96       156
          16       0.98      0.95      0.96       152
          17       0.90      0.95      0.93       147
          18       0.97      0.99      0.98       146
          19       0.98      0.95      0.97       150
          20       0.99      0.95      0.97       154
          21       0.95      0.96      0.95       141
          22       0.97      0.99      0.98       145
          23       0.96      0.96      0.96       136
          24       0.95      0.97      0.96       149
          25       0.98      0.96      0.97       128

    accuracy                           0.96      3734
   macro avg       0.96      0.95      0.95      3734
weighted avg       0.96      0.96      0.96      3734

* Default model accuracy: 0.9036 --> Tuned model accuracy: 0.9550
* Precision, recall, and F1-score also improved after tuning.
* Hyperparameter tuning (neurons, activation, optimizer, learning rate) boosted performance and helped the model generalize better.

In [31]:
# Hyperparameter tuning has a direct positive impact on model performance, making the ANN more accurate and reliable for classifying alphabets.